--- Makefile.orig	2026-04-04 20:06:56.494594000 -0400
+++ Makefile	2026-04-04 15:31:56.410107900 -0400
@@ -96,7 +96,7 @@
 #
 #
 #
-SEP=echo "\033[41;1m   $@   \033[0m"
+SEP=printf "\033[41;1m   $@   \033[0m"
 
 #
 # standard packages
@@ -1440,6 +1440,8 @@
 		-DOPENSSL_INCLUDE_DIR=$(TOP)/openssl-1.1/include \
 		-DOPENSSL_CRYPTO_LIBRARY=$(TOP)/openssl-1.1/libcrypto.so \
 		-DOPENSSL_SSL_LIBRARY=$(TOP)/openssl-1.1/libssl.so \
+		-DSTRPTIME_WORKS_EXITCODE="PLEASE_FILL_OUT-FAILED_TO_RUN" \
+		-DSTRPTIME_WORKS_EXITCODE__TRYRUN_OUTPUT="PLEASE_FILL_OUT-NOTFOUND" -Hforce \
 		-DLIBYAML_DIR=$(TOP)/libyaml \
 		-DLIBYAML_INCLUDE_DIR=$(TOP)/libyaml/include \
 		-DLIBYAML_LIBRARY=$(TOP)/libyaml/src/.libs/libyaml.a \
@@ -1617,7 +1619,7 @@
 
 libnfnetlink/stamp-h1:
 # tomatoraf.com, Victek
-	cd $(TOP)/libnfnetlink && CC=$(CC) STRIP=$(STRIP) \
+	cd $(TOP)/libnfnetlink && CC=$(CC) STRIP=$(CROSS_COMPILE)strip \
 		CFLAGS="-Os -Wall $(EXTRACFLAGS) -ffunction-sections -fdata-sections" \
 		LDFLAGS="-ffunction-sections -fdata-sections -Wl,--gc-sections" \
 		$(CONFIGURE) --prefix=/usr --enable-shared --enable-static
@@ -1879,6 +1881,7 @@
 
 libdaemon: libdaemon/stamp-h1
 	$(MAKE) -C $@ && $(MAKE) $@-stage
+	rm -f $(STAGEDIR)/usr/lib/libdaemon.la
 
 libdaemon-install: libdaemon
 	install -D libdaemon/libdaemon/.libs/libdaemon.so.0.5.0 $(INSTALLDIR)/libdaemon/usr/lib/libdaemon.so.0.5.0
@@ -1961,7 +1964,7 @@
 
 radvd/stamp-h1:
 	cd radvd && autoreconf -fi && \
-	CFLAGS="-Os $(EXTRACFLAGS) -ffunction-sections -fdata-sections" \
+	CFLAGS="-Os $(EXTRACFLAGS) -ffunction-sections -fdata-sections -std=gnu99" \
 	LDFLAGS="-ffunction-sections -fdata-sections -Wl,--gc-sections $(EXTRALDFLAGS)" \
 	$(CONFIGURE) --prefix="" --disable-dependency-tracking $(if $(RTCONFIG_BCMARM),,--without-stack-protector) \
 	DAEMON_CFLAGS="-I$(TOP)/libdaemon" \
@@ -2091,7 +2094,7 @@
 	$(MAKE) -C accel-pptpd server_install
 
 pptpd/stamp-h1:
-	cd $(TOP)/pptpd && $(CONFIGURE) --prefix=$(INSTALLDIR)/pptpd --enable-bcrelay CC=$(CC) STRIP=$(STRIP) AR=$(AR) LD=$(LD) NM=$(NM) RANLIB=$(RANLIB)
+	cd $(TOP)/pptpd && $(CONFIGURE) --prefix=$(INSTALLDIR)/pptpd --enable-bcrelay CC=$(CC) STRIP=$(CROSS_COMPILE)strip AR=$(AR) LD=$(LD) NM=$(NM) RANLIB=$(RANLIB)
 	touch $@
 
 pptpd: pptpd/stamp-h1
@@ -2912,7 +2915,7 @@
 
 openpam/Makefile:
 	( cd openpam && ./autogen.sh && \
-		LDFLAGS=-ldl \
+		LDFLAGS="-L$(TOOLCHAIN)/arm-brcm-linux-uclibcgnueabi/sysroot/usr/lib -L$(TOOLCHAIN)/lib" \
 		$(CONFIGURE) --prefix=/usr --bindir=/usr/sbin --libdir=/usr/lib \
 		--without-doc --with-pam-unix \
 	)
@@ -3131,7 +3134,7 @@
 	@rm -f pcre-8.31/stamp-h1
 
 libxml2/stamp-h1:
-	cd libxml2 && \
+	cd libxml2 && autoreconf -fsi && \
 	CC=$(CC) AR=$(AR) RANLIB=$(RANLIB) LD=$(LD) CFLAGS="-Os -Wall $(EXTRACFLAGS)" \
 	./$(CONFIGURE) --prefix=/usr --without-python --disable-dependency-tracking
 	touch $@
@@ -3210,7 +3213,7 @@
 curl: curl/Makefile
 	@$(MAKE) -C $@ $(PARALLEL_BUILD)
 
-curl/Makefile: curl/configure
+curl/Makefile:
 	@cd curl && CC=$(CC) \
 	CFLAGS="-Os -Wall -ffunction-sections -fdata-sections" \
 	./$(CONFIGURE) --prefix=/usr --bindir=/usr/sbin --libdir=/usr/lib \
@@ -3687,10 +3690,10 @@
 
 ipset-7/Makefile: ipset-7/configure
 	cd ipset-7 && \
-	libmnl_CFLAGS="-I$(STAGEDIR)/usr/include" \
-	libmnl_LIBS="-L$(STAGEDIR)/usr/lib -lmnl" \
+	libmnl_CFLAGS="-I$(TOP)/libmnl-1.0.4/include" \
+	libmnl_LIBS="-L$(TOP)/libmnl-1.0.4/src/.libs -lmnl" \
 	CFLAGS="-Os -Wall $(EXTRACFLAGS) -ffunction-sections -fdata-sections" \
-	LDFLAGS="-Wl,--gc-sections" \
+	LDFLAGS="-Wl,--gc-sections -L$(TOOLCHAIN)/arm-brcm-linux-uclibcgnueabi/sysroot/usr/lib -L$(TOOLCHAIN)/lib" \
 	$(CONFIGURE) --prefix=/usr \
 		--with-kmod=no --with-kbuild=$(LINUXDIR)
 
